# Generated by Django 4.2.11 on 2024-07-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_gamerecord_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='game_history',
        ),
        migrations.AddField(
            model_name='user',
            name='game_history',
            field=models.ManyToManyField(blank=True, related_name='players', to='user.gamerecord'),
        ),
    ]
