# Generated by Django 4.2.11 on 2024-07-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
        ('tournament', '0002_alter_tournament_final_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='semifinal_game1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semifinal_1', to='game.game'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='semifinal_game2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semifinal_2', to='game.game'),
        ),
    ]
