# Generated by Django 4.2.11 on 2024-07-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_tournament_semifinal_game1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='end_game_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
