# Generated by Django 4.2.11 on 2024-07-28 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
        ('tournament', '0004_tournament_end_game_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='final_game_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final', to='game.game'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='semifinal_game1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semifinal_1', to='game.game'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='semifinal_game2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semifinal_2', to='game.game'),
        ),
    ]
